# Generated by Django 6.0.1 on 2026-01-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_payment_link_remove_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name="ссылка на оплату"),
        ),
    ]
