# Generated by Django 6.0 on 2026-01-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите краткое описание урока",
                null=True,
                verbose_name="Краткое описание урока",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="materials/previews/"),
        ),
    ]
