# Generated by Django 6.0.1 on 2026-01-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_coursesubscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursesubscription",
            options={"verbose_name": "Подписка на курс", "verbose_name_plural": "Подписки на курсы"},
        ),
    ]
