# Generated by Django 6.0.1 on 2026-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_coursesubscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Цена курса"
            ),
        ),
    ]
