# Generated by Django 6.0.1 on 2026-01-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=10, max_digits=8, null=True, verbose_name="Цена курса"
            ),
        ),
    ]
