# Generated by Django 6.0.1 on 2026-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_alter_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name="Цена курса"),
        ),
    ]
